[devpdf]: Make test script more flexible.
* font/devpdf/tests/check-default-foundry.sh.in: Die with "hard error"
  if test script cannot locate the "Foundry" file.  Skip remainder of
  test (for fonts not in the PostScript Level 1/PDF "base 14") if the
  "URW" section of the "Foundry" file is absent.

diff --git a/font/devpdf/tests/check-default-foundry.sh.in b/font/devpdf/tests/check-default-foundry.sh.in
--- a/font/devpdf/tests/check-default-foundry.sh.in
+++ b/font/devpdf/tests/check-default-foundry.sh.in
@@ -90,6 +90,21 @@ then
     exit 77 # skip
 fi
 
+foundry="$devpdf_fontbuilddir"/Foundry
+
+if ! test -f "$foundry"
+then
+    echo "cannot locate Foundry file at $foundry" >&2
+    exit 99 # hard error
+fi
+
+if ! grep "BEGIN URW" "$foundry"
+then
+    echo "URW fonts not available; skipping check for any further" \
+         "fonts in the default foundry" >&2
+    exit 77 # skip
+fi
+
 for f in $supplementary_fonts
 do
     printf "checking for font description %s...\n" "$f" >&2
